"""fix migrations

Revision ID: c391431a9735
Revises: 47a823dd5c81
Create Date: 2025-06-03 09:52:07.916129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c391431a9735'
down_revision: Union[str, None] = '47a823dd5c81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('task_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'notifications', 'tasks', ['task_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'task_id')
    # ### end Alembic commands ###
